# Template author's notes
# -----------------------------------------------------------------------------------------
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# ------------------------------------------------------------------------------------------

# ---------------------------
# Site identity
# ---------------------------
title: Oltre il Copilota
subtitle: Guide ed esperimenti sull'AI Microsoft
description: >-
  Blog tecnico su tecnologie AI Microsoft, in particolare Copilot Studio, 
  Azure AI Foundry e Microsoft 365 Copilot.
locale: "it"
title_separator: "·"

# ---------------------------
# URLs
# ---------------------------
url: "https://oltreilcopilota.it/"
baseurl: ""
repository: "lucapagliari/lucapagliari.github.io"

# ---------------------------
# Theme + skin
# ---------------------------
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: air 
# Optional masthead/logo
# masthead_title: "Oltre il Copilota"
# logo: "/assets/images/logo-88x88.png"

# ---------------------------
# UI options
# ---------------------------
breadcrumbs: true
paginate: 5
paginate_path: /page:num/
read_time: true
page_meta_separator: "•"
enable_copy_code_button: true

# ---------------------------
# Search
# ---------------------------
search: true
search_provider: "lunr"

# ---------------------------
# SEO & social
# ---------------------------
twitter_username: username
github_username: username
# og_image: "/assets/images/og-default.png"
# google_site_verification: ""
# bing_site_verification: ""
# google_analytics: "G-XXXXXXX"

# ---------------------------
# Comments
# ---------------------------
comments:
  provider: false

# ---------------------------
# Build & Markdown
# ---------------------------
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
timezone: Europe/Rome

# ---------------------------
# Plugins (GitHub Pages–allowed)
# ---------------------------
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-gist
  - jemoji

# ---------------------------
# Collections (optional)
# ---------------------------
# collections:
#   projects:
#     output: true
#     permalink: /:collection/:name/

# ---------------------------
# Defaults
# ---------------------------
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# ---------------------------
# Author 
# ---------------------------
author:
  name   : "Luca Pagliari"
  avatar : "/assets/images/avatar.jpg"
  bio    : >-
    Microft Certified Trainer. Curioso per natura, mi piace studiare e sperimentare nuove tecnologie. 
    Se hai un’opinione diversa o un esempio migliore, contattami!
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/lucapagliari/"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/lucapagliari"


# ---------------------------
# Excludes & include cache
# ---------------------------
include:
  - _pages

# ---------------------------
# Caching
# ---------------------------
jekyll-include-cache:
  enabled: true



# footer:
#   links:
#     - label: "Twitter"
#       icon: "fab fa-fw fa-twitter-square"
#       url: "https://twitter.com/"
#     - label: "GitHub"
#       icon: "fab fa-fw fa-github"
#       url: "https://github.com/"
#     - label: "Instagram"
#       icon: "fab fa-fw fa-instagram"
#       url: "https://instagram.com/"


# category_archive:
#   type: liquid
#   path: /categories/
# tag_archive:
#   type: liquid
#   path: /tags/
